Make the PDF building compatible with fop version 1.1, which is the latest version.  This fixes errors that looked like
org.apache.fop.apps.FOPException: file:/C:/Documents%20and%20Settings/Dave/My%20Documents/logo-cvs/logo/manual/logohelp.fo:2:19711: Error(2/19711): No element mapping definition found for (Namespace URI: "http://xml.apache.org/fop/extensions", Local Name: "destination")


git-svn-id: https://svn.code.sf.net/p/fmslogo/source@3665 9d0050d7-00b0-40f9-871c-8e02cbd5794f